add_newline = true

format = """
$os\
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$cmd_duration\
$line_break\
$character\
"""

[os]
disabled = false
style = "bg:#D03E35 fg:#000000 bold"
format = "[ $symbol ]($style)"

[os.symbols]
Arch = ""
Linux = ""
Ubuntu = ""
Macos = ""

[username]
show_always = true
style_user = "bold #D03E35"
style_root = "bold #ff0000"
format = "[ $user]($style)"

[hostname]
ssh_only = false
style = "bold #444444"
format = "[@$hostname]($style) "
trim_at = ""

[directory]
style = "#E0E0E0"
truncation_length = 3
truncation_symbol = "…/"
read_only = " "
format = "[ \\[$path\\]]($style)($read_only) "

[git_branch]
symbol = " "
style = "bold #666666"
format = "[$symbol$branch]($style) "

[git_status]
style = "bold #D03E35"
format = "([$all_status$ahead_behind]($style) )"

[cmd_duration]
min_time = 2000
style = "bold #E0E0E0"
format = "[ \\[ $duration\\]]($style) "

[line_break]
disabled = false

[character]
success_symbol = "[└─>](bold #D03E35)"
error_symbol = "[└─  ](bold #ff0000)"